# -*- coding: utf-8 -*-
"""Aplikasi Deteksi Penambat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FePsFkfz2_itVUMYbMMgwutYRSTGlEy
"""

import streamlit as st
import cv2
import pandas as pd
import numpy as np
from ultralytics import YOLO
from collections import defaultdict, Counter
import tempfile
import os
from PIL import Image

# --- KONFIGURASI HALAMAN ---
st.set_page_config(page_title="Railway Fastener Monitoring", layout="wide")

st.markdown("""
    <style>
    .main {
        background-color: #f5f5f5;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    </style>
    """, unsafe_allow_name_html=True)

st.title("🚊 Sistem Monitoring Penambat Rel (Tesis)")
st.sidebar.title("Pengaturan Aplikasi")

# --- LOAD MODEL ---
@st.cache_resource
def load_model():
    # Pastikan file best.pt juga diupload ke GitHub
    return YOLO("best.pt")

try:
    model = load_model()
except Exception as e:
    st.error(f"Gagal memuat model: {e}. Pastikan file 'best.pt' sudah diunggah.")

# --- SIDEBAR: UPLOAD & PARAMETER ---
uploaded_video = st.sidebar.file_uploader("Upload Video Rel", type=["mp4", "avi", "mov"])
conf_threshold = st.sidebar.slider("Confidence Threshold", 0.1, 1.0, 0.2)
process_button = st.sidebar.button("Mulai Analisis Video")

# --- LOGIKA UTAMA ---
if uploaded_video is not None:
    # Simpan ke file sementara
    tfile = tempfile.NamedTemporaryFile(delete=False)
    tfile.write(uploaded_video.read())

    if process_button:
        cap = cv2.VideoCapture(tfile.name)
        width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

        # Penampung Hasil
        track_history = defaultdict(list)
        counted_ids = set()
        summary_counts = Counter()
        captured_images = [] # Untuk galeri

        y_ref = int(0.50 * height)

        # Area Dashboard Real-time
        col1, col2 = st.columns([2, 1])
        st_frame = col1.empty()
        st_metrics = col2.empty()

        st.info("Sedang memproses... Harap tunggu hingga selesai.")

        # Jalankan Tracking
        results = model.track(source=tfile.name, persist=True, imgsz=640, stream=True, conf=conf_